services:
  - type: web
    name: nahuatl-backend
    env: docker
    rootDir: .
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_TRANSLATE_MODEL
        value: gpt-4o-mini
      - key: OPENAI_TRANSCRIBE_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EXTRACT_MODEL
        value: gpt-4o-mini
      - key: CORS_ORIGINS
        value: "*"
